/********************************************
Copyright  2015, SN Servicing, Inc.

THIS FILE WAS AUTO-GENERATED BY A TOOL.
DO NOT EDIT THE CONTENTS MANUALLY.
********************************************/

using System;
using System.Data.SqlClient;
using System.Runtime.Serialization;

namespace Snsc.Database.Core
{
    /// <summary>
    /// SPEW Core.SecureShare.SecureShare_CreateExternalUser
    /// Generated: 2015-07-24 20:01 (utc) on eur-sql-stg by jprofumo.
    /// </summary>
    /// <remarks>
    /// Provides a wrapper for execution of the CreateExternalUser stored procedure.
    /// </remarks>
    [Serializable]
    public class SecureShare_CreateExternalUser : Snsc.Base.Data.StoredProcedureExecutorBase
    {
        // Private instance of the nested Parameters class
        private SecureShare_CreateExternalUserParameters __paramsInstance = null;

        /// <summary>
        /// Constructor.
        /// </summary>
        public SecureShare_CreateExternalUser()
        {
            Init();
        }

        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="cn">SqlConnection to use when executing the procedure.</param>
        public SecureShare_CreateExternalUser(SqlConnection cn) : base(cn)
        {
            Init();
        }

        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="cn">SqlConnection to use when executing the procedure.</param>
        /// <param name="tx">SqlTransaction to use when executing the procedure.</param>
        public SecureShare_CreateExternalUser(SqlConnection cn, SqlTransaction tx) : base(cn, tx)
        {
            Init();
        }

        /// <summary>
        /// Special constructor for DeSerialization.
        /// </summary>
        protected SecureShare_CreateExternalUser(SerializationInfo info, StreamingContext context) : base(info, context)
        {
        }

        /// <summary>
        /// Parameters for the procedure.
        /// </summary>
        public SecureShare_CreateExternalUserParameters Parameters
        {
            get
            {
                if (this.__paramsInstance == null)
                    throw new Snsc.Base.Data.ParametersNotInitializedException(this);
                return this.__paramsInstance;
            }
        }

        /// <summary>Must be called before calling any Execute... method.</summary>
        public Snsc.Base.Data.StoredProcedureExecutorBase VersionInfo23FCD5A4228AA1E62EFCF937DA3EB258()
        { this.VersionInfoChecked__ = true; return this; }

        /// <summary>Must be called before calling any Execute... method.</summary>
        public Snsc.Base.Data.StoredProcedureExecutorBase VersionInfo434660238()
        { this.VersionInfoChecked__ = true; return this; }

        /// <summary>
        /// Sets up parameters and adds them to the Command object.
        /// </summary>
        protected override void InitializeParameters()
        {
            __paramsInstance = new SecureShare_CreateExternalUserParameters(Command);
            this.Parameters.Reset();
        }

        private void Init()
        {
            this.dbname = "Core";
            this.procname = "[SecureShare].[CreateExternalUser]";
            this.versionInfo__ = 434660238;
            this.md5VersionInfo = "23FCD5A4228AA1E62EFCF937DA3EB258";
            InitializeParameters();
        }

        /// <summary>
        /// Nested class containing the parameters for the procedure.
        /// </summary>
        [Serializable]
        public class SecureShare_CreateExternalUserParameters
        {
            private SqlParameterCollection __paramsCollection = null;

            private SqlParameter _private__returnvalue__ = null;

            private SqlParameter _private_FirstName_ = null;

            private SqlParameter _private_LastName_ = null;

            private SqlParameter _private_UserAccess_ = null;

            private SqlParameter _private_UserName_ = null;

            /// <summary>
            /// Constructor.
            /// </summary>
            public SecureShare_CreateExternalUserParameters(SqlCommand cmd)
            {
                // Grab ref to the parameters collection for use in the Reset() method.
                this.__paramsCollection = cmd.Parameters;
                SqlParameter p = null;
                //---- Parameter @UserName
                p = new SqlParameter(); p.ParameterName = "@UserName"; p.SqlDbType = System.Data.SqlDbType.VarChar; p.Direction = System.Data.ParameterDirection.Input; p.Size = 100; p.Precision = 0; p.Scale = 0; cmd.Parameters.Add(p); this._private_UserName_ = p;
                //---- Parameter @FirstName
                p = new SqlParameter(); p.ParameterName = "@FirstName"; p.SqlDbType = System.Data.SqlDbType.VarChar; p.Direction = System.Data.ParameterDirection.Input; p.Size = 100; p.Precision = 0; p.Scale = 0; cmd.Parameters.Add(p); this._private_FirstName_ = p;
                //---- Parameter @LastName
                p = new SqlParameter(); p.ParameterName = "@LastName"; p.SqlDbType = System.Data.SqlDbType.VarChar; p.Direction = System.Data.ParameterDirection.Input; p.Size = 100; p.Precision = 0; p.Scale = 0; cmd.Parameters.Add(p); this._private_LastName_ = p;
                //---- Parameter @UserAccess
                p = new SqlParameter(); p.ParameterName = "@UserAccess"; p.SqlDbType = System.Data.SqlDbType.Int; p.Direction = System.Data.ParameterDirection.Input; p.Size = 0; p.Precision = 10; p.Scale = 0; cmd.Parameters.Add(p); this._private_UserAccess_ = p;
                // Add hard-coded return value
                p = new SqlParameter(); p.ParameterName = "@RETURN_VALUE"; p.SqlDbType = System.Data.SqlDbType.Int; p.Direction = System.Data.ParameterDirection.ReturnValue; cmd.Parameters.Add(p); this._private__returnvalue__ = p;
            }

            public SqlParameter FirstName_
            { get { return _private_FirstName_; } }

            public SqlParameter LastName_
            { get { return _private_LastName_; } }

            public SqlParameter ReturnValue__
            { get { return this._private__returnvalue__; } }

            public SqlParameter UserAccess_
            { get { return _private_UserAccess_; } }

            /// <summary>
            /// Provides access to parameters by name.
            /// </summary>
            public SqlParameter UserName_
            { get { return _private_UserName_; } }

            /// <summary>
            /// Sets value of all SqlParameters to DBNull.Value.
            /// </summary>
            public void Reset()
            {
                foreach (SqlParameter p in __paramsCollection)
                {
                    p.Value = DBNull.Value;
                }
            }
        }
    }
}