/********************************************
Copyright  2015, SN Servicing, Inc.

THIS FILE WAS AUTO-GENERATED BY A TOOL.
DO NOT EDIT THE CONTENTS MANUALLY.
********************************************/

using System;
using System.Data.SqlClient;
using System.Runtime.Serialization;

namespace Snsc.Database.Core
{
    /// <summary>
    /// SPEW Core.SecureShare.SecureShare_GetExternalUser
    /// Generated: 2015-07-24 16:30 (utc) on eur-sql-stg by jprofumo.
    /// </summary>
    /// <remarks>
    /// Provides a wrapper for execution of the GetExternalUser stored procedure.
    /// </remarks>
    [Serializable]
    public class SecureShare_GetExternalUser : Snsc.Base.Data.StoredProcedureExecutorBase
    {
        // Private instance of the nested Parameters class
        private SecureShare_GetExternalUserParameters __paramsInstance = null;

        /// <summary>
        /// Constructor.
        /// </summary>
        public SecureShare_GetExternalUser()
        {
            Init();
        }

        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="cn">SqlConnection to use when executing the procedure.</param>
        public SecureShare_GetExternalUser(SqlConnection cn) : base(cn)
        {
            Init();
        }

        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="cn">SqlConnection to use when executing the procedure.</param>
        /// <param name="tx">SqlTransaction to use when executing the procedure.</param>
        public SecureShare_GetExternalUser(SqlConnection cn, SqlTransaction tx) : base(cn, tx)
        {
            Init();
        }

        /// <summary>
        /// Special constructor for DeSerialization.
        /// </summary>
        protected SecureShare_GetExternalUser(SerializationInfo info, StreamingContext context) : base(info, context)
        {
        }

        /// <summary>
        /// Parameters for the procedure.
        /// </summary>
        public SecureShare_GetExternalUserParameters Parameters
        {
            get
            {
                if (this.__paramsInstance == null)
                    throw new Snsc.Base.Data.ParametersNotInitializedException(this);
                return this.__paramsInstance;
            }
        }

        /// <summary>Must be called before calling any Execute... method.</summary>
        public Snsc.Base.Data.StoredProcedureExecutorBase VersionInfo298014800()
        { this.VersionInfoChecked__ = true; return this; }

        /// <summary>Must be called before calling any Execute... method.</summary>
        public Snsc.Base.Data.StoredProcedureExecutorBase VersionInfo74EDF1772145DF672EB351E01FE75294()
        { this.VersionInfoChecked__ = true; return this; }

        /// <summary>
        /// Sets up parameters and adds them to the Command object.
        /// </summary>
        protected override void InitializeParameters()
        {
            __paramsInstance = new SecureShare_GetExternalUserParameters(Command);
            this.Parameters.Reset();
        }

        private void Init()
        {
            this.dbname = "Core";
            this.procname = "[SecureShare].[GetExternalUser]";
            this.versionInfo__ = 298014800;
            this.md5VersionInfo = "74EDF1772145DF672EB351E01FE75294";
            InitializeParameters();
        }

        /// <summary>
        /// Nested class containing the parameters for the procedure.
        /// </summary>
        [Serializable]
        public class SecureShare_GetExternalUserParameters
        {
            private SqlParameterCollection __paramsCollection = null;

            private SqlParameter _private__returnvalue__ = null;

            private SqlParameter _private_ExternalUserId_ = null;

            private SqlParameter _private_UserName_ = null;

            /// <summary>
            /// Constructor.
            /// </summary>
            public SecureShare_GetExternalUserParameters(SqlCommand cmd)
            {
                // Grab ref to the parameters collection for use in the Reset() method.
                this.__paramsCollection = cmd.Parameters;
                SqlParameter p = null;
                //---- Parameter @UserName
                p = new SqlParameter(); p.ParameterName = "@UserName"; p.SqlDbType = System.Data.SqlDbType.VarChar; p.Direction = System.Data.ParameterDirection.Input; p.Size = 100; p.Precision = 0; p.Scale = 0; cmd.Parameters.Add(p); this._private_UserName_ = p;
                //---- Parameter @ExternalUserId
                p = new SqlParameter(); p.ParameterName = "@ExternalUserId"; p.SqlDbType = System.Data.SqlDbType.UniqueIdentifier; p.Direction = System.Data.ParameterDirection.Input; p.Size = 0; p.Precision = 0; p.Scale = 0; cmd.Parameters.Add(p); this._private_ExternalUserId_ = p;
                // Add hard-coded return value
                p = new SqlParameter(); p.ParameterName = "@RETURN_VALUE"; p.SqlDbType = System.Data.SqlDbType.Int; p.Direction = System.Data.ParameterDirection.ReturnValue; cmd.Parameters.Add(p); this._private__returnvalue__ = p;
            }

            /// <summary>@ExternalUserId uniqueidentifier || Direction: Input || Prec: 0 || Scale: 0</summary>
            public SqlParameter ExternalUserId_
            { get { return _private_ExternalUserId_; } }

            /// <summary>@__returnvalue__ int || Direction: ReturnValue</summary>
            public SqlParameter ReturnValue__
            { get { return this._private__returnvalue__; } }

            /// <summary>@UserName varchar(100) || Direction: Input || Prec: 0 || Scale: 0</summary>
            public SqlParameter UserName_
            { get { return _private_UserName_; } }

            /// <summary>
            /// Sets value of all SqlParameters to DBNull.Value.
            /// </summary>
            public void Reset()
            {
                foreach (SqlParameter p in __paramsCollection)
                {
                    p.Value = DBNull.Value;
                }
            }
        }
    }
}