/********************************************
Copyright  2015, SN Servicing, Inc.

THIS FILE WAS AUTO-GENERATED BY A TOOL.
DO NOT EDIT THE CONTENTS MANUALLY.
********************************************/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Runtime.Serialization;

namespace Snsc.Database.Core
{
	#region Class SecureShare_up_SDIs_FileSharingZonesForUser
	/// <summary>
	/// SPEW Core.SecureShare.SecureShare_up_SDIs_FileSharingZonesForUser
	/// Generated: 2015-07-23 22:03 (utc) on eur-sql-stg by jprofumo.
	/// </summary>
	/// <remarks>
	/// Provides a wrapper for execution of the up_SDIs_FileSharingZonesForUser stored procedure.
	/// </remarks>
	[Serializable]
	public class SecureShare_up_SDIs_FileSharingZonesForUser : Snsc.Base.Data.StoredProcedureExecutorBase
	{
		private void Init()
		{
			this.dbname = "Core";
			this.procname = "[SecureShare].[up_SDIs_FileSharingZonesForUser]";
			this.versionInfo__ = 1997579260;
			this.md5VersionInfo = "BC701928F4D3FAAC0F72E84893A7179";
			InitializeParameters();
		}
		
		#region Class SecureShare_up_SDIs_FileSharingZonesForUser Constructors
		/// <summary>
		/// Constructor.
		/// </summary>
		public SecureShare_up_SDIs_FileSharingZonesForUser()
		{
			Init();
		}

		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="cn">SqlConnection to use when executing the procedure.</param>
		public SecureShare_up_SDIs_FileSharingZonesForUser(SqlConnection cn) : base(cn)
		{
			Init();
		}

		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="cn">SqlConnection to use when executing the procedure.</param>
		/// <param name="tx">SqlTransaction to use when executing the procedure.</param>
		public SecureShare_up_SDIs_FileSharingZonesForUser(SqlConnection cn, SqlTransaction tx) : base(cn, tx)
		{
			Init();
		}

		/// <summary>
		/// Special constructor for DeSerialization.
		/// </summary>
		protected SecureShare_up_SDIs_FileSharingZonesForUser(SerializationInfo info, StreamingContext context) : base(info, context)
		{
		}
		#endregion

		// Private instance of the nested Parameters class
		private SecureShare_up_SDIs_FileSharingZonesForUserParameters __paramsInstance = null;

		/// <summary>
		/// Parameters for the procedure.
		/// </summary>
		public SecureShare_up_SDIs_FileSharingZonesForUserParameters Parameters
		{
			get
			{
				if(this.__paramsInstance == null)
					throw new Snsc.Base.Data.ParametersNotInitializedException(this);
				return this.__paramsInstance;
			}
		}

		/// <summary>
		/// Sets up parameters and adds them to the Command object.
		/// </summary>
		protected override void InitializeParameters()
		{
			__paramsInstance = new SecureShare_up_SDIs_FileSharingZonesForUserParameters(Command);
			this.Parameters.Reset();
		}

		#region SecureShare_up_SDIs_FileSharingZonesForUser Parameters class
		/// <summary>
		/// Nested class containing the parameters for the procedure.
		/// </summary>
		[Serializable]
		public class SecureShare_up_SDIs_FileSharingZonesForUserParameters
		{
			private SqlParameterCollection __paramsCollection = null;

			/// <summary>
			/// Sets value of all SqlParameters to DBNull.Value.
			/// </summary>
			public void Reset()
			{
				foreach(SqlParameter p in __paramsCollection)
				{
					p.Value = DBNull.Value;
				}
			}

			#region SecureShare_up_SDIs_FileSharingZonesForUser Parameters Initialization
			/// <summary>
			/// Constructor.
			/// </summary>
			public SecureShare_up_SDIs_FileSharingZonesForUserParameters(SqlCommand cmd)
			{
				// Grab ref to the parameters collection for use in the Reset() method.
				this.__paramsCollection = cmd.Parameters;
				SqlParameter p = null;
				//---- Parameter @AspNetUserID
				p = new SqlParameter(); p.ParameterName = "@AspNetUserID"; p.SqlDbType = System.Data.SqlDbType.UniqueIdentifier; p.Direction = System.Data.ParameterDirection.Input; p.Size = 0; p.Precision = 0; p.Scale = 0; cmd.Parameters.Add(p); this._private_AspNetUserID_ = p;
				// Add hard-coded return value
				p = new SqlParameter(); p.ParameterName = "@RETURN_VALUE"; p.SqlDbType = System.Data.SqlDbType.Int; p.Direction = System.Data.ParameterDirection.ReturnValue; cmd.Parameters.Add(p); this._private__returnvalue__ = p;
			}
			#endregion
			private SqlParameter _private_AspNetUserID_ = null;
			private SqlParameter _private__returnvalue__ = null;

			/// <summary>
			/// Provides access to parameters by name.
			/// </summary>
			public SqlParameter this[string paramName]
			{
				get
				{
					string idx = paramName.Replace("@", "").ToLower();
					SqlParameter retval = null;
					switch(idx)
					{
						case "aspnetuserid": retval = this._private_AspNetUserID_; break;
						case "__returnvalue__": retval = this._private__returnvalue__; break;
					}
					return retval;
				}
			}

			/// <summary>@AspNetUserID uniqueidentifier || Direction: Input || Prec: 0 || Scale: 0</summary>
			public SqlParameter AspNetUserID_ { get { return _private_AspNetUserID_; } }
			/// <summary>@__returnvalue__ int || Direction: ReturnValue</summary>
			public SqlParameter ReturnValue__ { get { return this._private__returnvalue__; } }
		}
		#endregion

		/// <summary>Must be called before calling any Execute... method.</summary>
		public Snsc.Base.Data.StoredProcedureExecutorBase VersionInfo1997579260()
		{ this.VersionInfoChecked__ = true; return this; }

		/// <summary>Must be called before calling any Execute... method.</summary>
		public Snsc.Base.Data.StoredProcedureExecutorBase VersionInfoBC701928F4D3FAAC0F72E84893A7179()
		{ this.VersionInfoChecked__ = true; return this; }
	}
	#endregion
}
