/********************************************
Copyright  2015, SN Servicing, Inc.

THIS FILE WAS AUTO-GENERATED BY A TOOL.
DO NOT EDIT THE CONTENTS MANUALLY.
********************************************/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Runtime.Serialization;

namespace Snsc.Database.Core
{
	#region Class SecureShare_up_SDIiu_sdiNewFileNotification
	/// <summary>
	/// SPEW Core.SecureShare.SecureShare_up_SDIiu_sdiNewFileNotification
	/// Generated: 2015-08-26 16:18 (utc) on eur-sql-stg by jprofumo.
	/// </summary>
	/// <remarks>
	/// Provides a wrapper for execution of the up_SDIiu_sdiNewFileNotification stored procedure.
	/// </remarks>
	[Serializable]
	public class SecureShare_up_SDIiu_sdiNewFileNotification : Snsc.Base.Data.StoredProcedureExecutorBase
	{
		private void Init()
		{
			this.dbname = "Core";
			this.procname = "[SecureShare].[up_SDIiu_sdiNewFileNotification]";
			this.versionInfo__ = 1299357082;
			this.md5VersionInfo = "BF1417AF39EDC17442E0DFEFD763508A";
			InitializeParameters();
		}
		
		#region Class SecureShare_up_SDIiu_sdiNewFileNotification Constructors
		/// <summary>
		/// Constructor.
		/// </summary>
		public SecureShare_up_SDIiu_sdiNewFileNotification()
		{
			Init();
		}

		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="cn">SqlConnection to use when executing the procedure.</param>
		public SecureShare_up_SDIiu_sdiNewFileNotification(SqlConnection cn) : base(cn)
		{
			Init();
		}

		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="cn">SqlConnection to use when executing the procedure.</param>
		/// <param name="tx">SqlTransaction to use when executing the procedure.</param>
		public SecureShare_up_SDIiu_sdiNewFileNotification(SqlConnection cn, SqlTransaction tx) : base(cn, tx)
		{
			Init();
		}

		/// <summary>
		/// Special constructor for DeSerialization.
		/// </summary>
		protected SecureShare_up_SDIiu_sdiNewFileNotification(SerializationInfo info, StreamingContext context) : base(info, context)
		{
		}
		#endregion

		// Private instance of the nested Parameters class
		private SecureShare_up_SDIiu_sdiNewFileNotificationParameters __paramsInstance = null;

		/// <summary>
		/// Parameters for the procedure.
		/// </summary>
		public SecureShare_up_SDIiu_sdiNewFileNotificationParameters Parameters
		{
			get
			{
				if(this.__paramsInstance == null)
					throw new Snsc.Base.Data.ParametersNotInitializedException(this);
				return this.__paramsInstance;
			}
		}

		/// <summary>
		/// Sets up parameters and adds them to the Command object.
		/// </summary>
		protected override void InitializeParameters()
		{
			__paramsInstance = new SecureShare_up_SDIiu_sdiNewFileNotificationParameters(Command);
			this.Parameters.Reset();
		}

		#region SecureShare_up_SDIiu_sdiNewFileNotification Parameters class
		/// <summary>
		/// Nested class containing the parameters for the procedure.
		/// </summary>
		[Serializable]
		public class SecureShare_up_SDIiu_sdiNewFileNotificationParameters
		{
			private SqlParameterCollection __paramsCollection = null;

			/// <summary>
			/// Sets value of all SqlParameters to DBNull.Value.
			/// </summary>
			public void Reset()
			{
				foreach(SqlParameter p in __paramsCollection)
				{
					p.Value = DBNull.Value;
				}
			}

			#region SecureShare_up_SDIiu_sdiNewFileNotification Parameters Initialization
			/// <summary>
			/// Constructor.
			/// </summary>
			public SecureShare_up_SDIiu_sdiNewFileNotificationParameters(SqlCommand cmd)
			{
				// Grab ref to the parameters collection for use in the Reset() method.
				this.__paramsCollection = cmd.Parameters;
				SqlParameter p = null;
				//---- Parameter @AspNetUserID
				p = new SqlParameter(); p.ParameterName = "@AspNetUserID"; p.SqlDbType = System.Data.SqlDbType.UniqueIdentifier; p.Direction = System.Data.ParameterDirection.Input; p.Size = 0; p.Precision = 0; p.Scale = 0; cmd.Parameters.Add(p); this._private_AspNetUserID_ = p;
				//---- Parameter @AmsUserID
				p = new SqlParameter(); p.ParameterName = "@AmsUserID"; p.SqlDbType = System.Data.SqlDbType.BigInt; p.Direction = System.Data.ParameterDirection.Input; p.Size = 0; p.Precision = 19; p.Scale = 0; cmd.Parameters.Add(p); this._private_AmsUserID_ = p;
				//---- Parameter @DateLastNotificationSentUTC
				p = new SqlParameter(); p.ParameterName = "@DateLastNotificationSentUTC"; p.SqlDbType = System.Data.SqlDbType.DateTime; p.Direction = System.Data.ParameterDirection.Input; p.Size = 0; p.Precision = 0; p.Scale = 0; cmd.Parameters.Add(p); this._private_DateLastNotificationSentUTC_ = p;
				//---- Parameter @nullMap
				p = new SqlParameter(); p.ParameterName = "@nullMap"; p.SqlDbType = System.Data.SqlDbType.VarBinary; p.Direction = System.Data.ParameterDirection.Input; p.Size = 1; p.Precision = 0; p.Scale = 0; cmd.Parameters.Add(p); this._private_nullMap_ = p;
				// Add hard-coded return value
				p = new SqlParameter(); p.ParameterName = "@RETURN_VALUE"; p.SqlDbType = System.Data.SqlDbType.Int; p.Direction = System.Data.ParameterDirection.ReturnValue; cmd.Parameters.Add(p); this._private__returnvalue__ = p;
			}
			#endregion
			private SqlParameter _private_AspNetUserID_ = null;
			private SqlParameter _private_AmsUserID_ = null;
			private SqlParameter _private_DateLastNotificationSentUTC_ = null;
			private SqlParameter _private_nullMap_ = null;
			private SqlParameter _private__returnvalue__ = null;

			/// <summary>
			/// Provides access to parameters by name.
			/// </summary>
			public SqlParameter this[string paramName]
			{
				get
				{
					string idx = paramName.Replace("@", "").ToLower();
					SqlParameter retval = null;
					switch(idx)
					{
						case "aspnetuserid": retval = this._private_AspNetUserID_; break;
						case "amsuserid": retval = this._private_AmsUserID_; break;
						case "datelastnotificationsentutc": retval = this._private_DateLastNotificationSentUTC_; break;
						case "nullmap": retval = this._private_nullMap_; break;
						case "__returnvalue__": retval = this._private__returnvalue__; break;
					}
					return retval;
				}
			}

			/// <summary>@AspNetUserID uniqueidentifier || Direction: Input || Prec: 0 || Scale: 0</summary>
			public SqlParameter AspNetUserID_ { get { return _private_AspNetUserID_; } }
			/// <summary>@AmsUserID bigint || Direction: Input || Prec: 19 || Scale: 0</summary>
			public SqlParameter AmsUserID_ { get { return _private_AmsUserID_; } }
			/// <summary>@DateLastNotificationSentUTC datetime || Direction: Input || Prec: 0 || Scale: 0</summary>
			public SqlParameter DateLastNotificationSentUTC_ { get { return _private_DateLastNotificationSentUTC_; } }
			/// <summary>@nullMap varbinary(1) || Direction: Input || Prec: 0 || Scale: 0</summary>
			public SqlParameter nullMap_ { get { return _private_nullMap_; } }
			/// <summary>@__returnvalue__ int || Direction: ReturnValue</summary>
			public SqlParameter ReturnValue__ { get { return this._private__returnvalue__; } }
		}
		#endregion

		/// <summary>Must be called before calling any Execute... method.</summary>
		public Snsc.Base.Data.StoredProcedureExecutorBase VersionInfo1299357082()
		{ this.VersionInfoChecked__ = true; return this; }

		/// <summary>Must be called before calling any Execute... method.</summary>
		public Snsc.Base.Data.StoredProcedureExecutorBase VersionInfoBF1417AF39EDC17442E0DFEFD763508A()
		{ this.VersionInfoChecked__ = true; return this; }
	}
	#endregion
}
