/********************************************
Copyright  2015, SN Servicing, Inc.

THIS FILE WAS AUTO-GENERATED BY A TOOL.
DO NOT EDIT THE CONTENTS MANUALLY.
********************************************/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Runtime.Serialization;

namespace Snsc.Database.Core
{
	#region Class SecureShare_up_SDIs_sdiUsersByZone
	/// <summary>
	/// SPEW Core.SecureShare.SecureShare_up_SDIs_sdiUsersByZone
	/// Generated: 2015-08-26 16:18 (utc) on eur-sql-stg by jprofumo.
	/// </summary>
	/// <remarks>
	/// Provides a wrapper for execution of the up_SDIs_sdiUsersByZone stored procedure.
	/// </remarks>
	[Serializable]
	public class SecureShare_up_SDIs_sdiUsersByZone : Snsc.Base.Data.StoredProcedureExecutorBase
	{
		private void Init()
		{
			this.dbname = "Core";
			this.procname = "[SecureShare].[up_SDIs_sdiUsersByZone]";
			this.versionInfo__ = 1954863328;
			this.md5VersionInfo = "78542F7B6F2EC02342CAE7E175D7145";
			InitializeParameters();
		}
		
		#region Class SecureShare_up_SDIs_sdiUsersByZone Constructors
		/// <summary>
		/// Constructor.
		/// </summary>
		public SecureShare_up_SDIs_sdiUsersByZone()
		{
			Init();
		}

		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="cn">SqlConnection to use when executing the procedure.</param>
		public SecureShare_up_SDIs_sdiUsersByZone(SqlConnection cn) : base(cn)
		{
			Init();
		}

		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="cn">SqlConnection to use when executing the procedure.</param>
		/// <param name="tx">SqlTransaction to use when executing the procedure.</param>
		public SecureShare_up_SDIs_sdiUsersByZone(SqlConnection cn, SqlTransaction tx) : base(cn, tx)
		{
			Init();
		}

		/// <summary>
		/// Special constructor for DeSerialization.
		/// </summary>
		protected SecureShare_up_SDIs_sdiUsersByZone(SerializationInfo info, StreamingContext context) : base(info, context)
		{
		}
		#endregion

		// Private instance of the nested Parameters class
		private SecureShare_up_SDIs_sdiUsersByZoneParameters __paramsInstance = null;

		/// <summary>
		/// Parameters for the procedure.
		/// </summary>
		public SecureShare_up_SDIs_sdiUsersByZoneParameters Parameters
		{
			get
			{
				if(this.__paramsInstance == null)
					throw new Snsc.Base.Data.ParametersNotInitializedException(this);
				return this.__paramsInstance;
			}
		}

		/// <summary>
		/// Sets up parameters and adds them to the Command object.
		/// </summary>
		protected override void InitializeParameters()
		{
			__paramsInstance = new SecureShare_up_SDIs_sdiUsersByZoneParameters(Command);
			this.Parameters.Reset();
		}

		#region SecureShare_up_SDIs_sdiUsersByZone Parameters class
		/// <summary>
		/// Nested class containing the parameters for the procedure.
		/// </summary>
		[Serializable]
		public class SecureShare_up_SDIs_sdiUsersByZoneParameters
		{
			private SqlParameterCollection __paramsCollection = null;

			/// <summary>
			/// Sets value of all SqlParameters to DBNull.Value.
			/// </summary>
			public void Reset()
			{
				foreach(SqlParameter p in __paramsCollection)
				{
					p.Value = DBNull.Value;
				}
			}

			#region SecureShare_up_SDIs_sdiUsersByZone Parameters Initialization
			/// <summary>
			/// Constructor.
			/// </summary>
			public SecureShare_up_SDIs_sdiUsersByZoneParameters(SqlCommand cmd)
			{
				// Grab ref to the parameters collection for use in the Reset() method.
				this.__paramsCollection = cmd.Parameters;
				SqlParameter p = null;
				//---- Parameter @ZoneID
				p = new SqlParameter(); p.ParameterName = "@ZoneID"; p.SqlDbType = System.Data.SqlDbType.Int; p.Direction = System.Data.ParameterDirection.Input; p.Size = 0; p.Precision = 10; p.Scale = 0; cmd.Parameters.Add(p); this._private_ZoneID_ = p;
				// Add hard-coded return value
				p = new SqlParameter(); p.ParameterName = "@RETURN_VALUE"; p.SqlDbType = System.Data.SqlDbType.Int; p.Direction = System.Data.ParameterDirection.ReturnValue; cmd.Parameters.Add(p); this._private__returnvalue__ = p;
			}
			#endregion
			private SqlParameter _private_ZoneID_ = null;
			private SqlParameter _private__returnvalue__ = null;

			/// <summary>
			/// Provides access to parameters by name.
			/// </summary>
			public SqlParameter this[string paramName]
			{
				get
				{
					string idx = paramName.Replace("@", "").ToLower();
					SqlParameter retval = null;
					switch(idx)
					{
						case "zoneid": retval = this._private_ZoneID_; break;
						case "__returnvalue__": retval = this._private__returnvalue__; break;
					}
					return retval;
				}
			}

			/// <summary>@ZoneID int || Direction: Input || Prec: 10 || Scale: 0</summary>
			public SqlParameter ZoneID_ { get { return _private_ZoneID_; } }
			/// <summary>@__returnvalue__ int || Direction: ReturnValue</summary>
			public SqlParameter ReturnValue__ { get { return this._private__returnvalue__; } }
		}
		#endregion

		/// <summary>Must be called before calling any Execute... method.</summary>
		public Snsc.Base.Data.StoredProcedureExecutorBase VersionInfo1954863328()
		{ this.VersionInfoChecked__ = true; return this; }

		/// <summary>Must be called before calling any Execute... method.</summary>
		public Snsc.Base.Data.StoredProcedureExecutorBase VersionInfo78542F7B6F2EC02342CAE7E175D7145()
		{ this.VersionInfoChecked__ = true; return this; }
	}
	#endregion
}
