/********************************************
Copyright  2015, SN Servicing, Inc.

THIS FILE WAS AUTO-GENERATED BY A TOOL.
DO NOT EDIT THE CONTENTS MANUALLY.
********************************************/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Runtime.Serialization;

namespace Snsc.Database.Core
{
	#region Class SecureShare_up_SDId_sdiFileSharingZonePermission
	/// <summary>
	/// SPEW Core.SecureShare.SecureShare_up_SDId_sdiFileSharingZonePermission
	/// Generated: 2015-08-26 16:18 (utc) on eur-sql-stg by jprofumo.
	/// </summary>
	/// <remarks>
	/// Provides a wrapper for execution of the up_SDId_sdiFileSharingZonePermission stored procedure.
	/// </remarks>
	[Serializable]
	public class SecureShare_up_SDId_sdiFileSharingZonePermission : Snsc.Base.Data.StoredProcedureExecutorBase
	{
		private void Init()
		{
			this.dbname = "Core";
			this.procname = "[SecureShare].[up_SDId_sdiFileSharingZonePermission]";
			this.versionInfo__ = 1999107901;
			this.md5VersionInfo = "41E5AECAB43DEAF4B8CD635A4571489";
			InitializeParameters();
		}
		
		#region Class SecureShare_up_SDId_sdiFileSharingZonePermission Constructors
		/// <summary>
		/// Constructor.
		/// </summary>
		public SecureShare_up_SDId_sdiFileSharingZonePermission()
		{
			Init();
		}

		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="cn">SqlConnection to use when executing the procedure.</param>
		public SecureShare_up_SDId_sdiFileSharingZonePermission(SqlConnection cn) : base(cn)
		{
			Init();
		}

		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="cn">SqlConnection to use when executing the procedure.</param>
		/// <param name="tx">SqlTransaction to use when executing the procedure.</param>
		public SecureShare_up_SDId_sdiFileSharingZonePermission(SqlConnection cn, SqlTransaction tx) : base(cn, tx)
		{
			Init();
		}

		/// <summary>
		/// Special constructor for DeSerialization.
		/// </summary>
		protected SecureShare_up_SDId_sdiFileSharingZonePermission(SerializationInfo info, StreamingContext context) : base(info, context)
		{
		}
		#endregion

		// Private instance of the nested Parameters class
		private SecureShare_up_SDId_sdiFileSharingZonePermissionParameters __paramsInstance = null;

		/// <summary>
		/// Parameters for the procedure.
		/// </summary>
		public SecureShare_up_SDId_sdiFileSharingZonePermissionParameters Parameters
		{
			get
			{
				if(this.__paramsInstance == null)
					throw new Snsc.Base.Data.ParametersNotInitializedException(this);
				return this.__paramsInstance;
			}
		}

		/// <summary>
		/// Sets up parameters and adds them to the Command object.
		/// </summary>
		protected override void InitializeParameters()
		{
			__paramsInstance = new SecureShare_up_SDId_sdiFileSharingZonePermissionParameters(Command);
			this.Parameters.Reset();
		}

		#region SecureShare_up_SDId_sdiFileSharingZonePermission Parameters class
		/// <summary>
		/// Nested class containing the parameters for the procedure.
		/// </summary>
		[Serializable]
		public class SecureShare_up_SDId_sdiFileSharingZonePermissionParameters
		{
			private SqlParameterCollection __paramsCollection = null;

			/// <summary>
			/// Sets value of all SqlParameters to DBNull.Value.
			/// </summary>
			public void Reset()
			{
				foreach(SqlParameter p in __paramsCollection)
				{
					p.Value = DBNull.Value;
				}
			}

			#region SecureShare_up_SDId_sdiFileSharingZonePermission Parameters Initialization
			/// <summary>
			/// Constructor.
			/// </summary>
			public SecureShare_up_SDId_sdiFileSharingZonePermissionParameters(SqlCommand cmd)
			{
				// Grab ref to the parameters collection for use in the Reset() method.
				this.__paramsCollection = cmd.Parameters;
				SqlParameter p = null;
				//---- Parameter @ZonePermissionID
				p = new SqlParameter(); p.ParameterName = "@ZonePermissionID"; p.SqlDbType = System.Data.SqlDbType.Int; p.Direction = System.Data.ParameterDirection.Input; p.Size = 0; p.Precision = 10; p.Scale = 0; cmd.Parameters.Add(p); this._private_ZonePermissionID_ = p;
				// Add hard-coded return value
				p = new SqlParameter(); p.ParameterName = "@RETURN_VALUE"; p.SqlDbType = System.Data.SqlDbType.Int; p.Direction = System.Data.ParameterDirection.ReturnValue; cmd.Parameters.Add(p); this._private__returnvalue__ = p;
			}
			#endregion
			private SqlParameter _private_ZonePermissionID_ = null;
			private SqlParameter _private__returnvalue__ = null;

			/// <summary>
			/// Provides access to parameters by name.
			/// </summary>
			public SqlParameter this[string paramName]
			{
				get
				{
					string idx = paramName.Replace("@", "").ToLower();
					SqlParameter retval = null;
					switch(idx)
					{
						case "zonepermissionid": retval = this._private_ZonePermissionID_; break;
						case "__returnvalue__": retval = this._private__returnvalue__; break;
					}
					return retval;
				}
			}

			/// <summary>@ZonePermissionID int || Direction: Input || Prec: 10 || Scale: 0</summary>
			public SqlParameter ZonePermissionID_ { get { return _private_ZonePermissionID_; } }
			/// <summary>@__returnvalue__ int || Direction: ReturnValue</summary>
			public SqlParameter ReturnValue__ { get { return this._private__returnvalue__; } }
		}
		#endregion

		/// <summary>Must be called before calling any Execute... method.</summary>
		public Snsc.Base.Data.StoredProcedureExecutorBase VersionInfo1999107901()
		{ this.VersionInfoChecked__ = true; return this; }

		/// <summary>Must be called before calling any Execute... method.</summary>
		public Snsc.Base.Data.StoredProcedureExecutorBase VersionInfo41E5AECAB43DEAF4B8CD635A4571489()
		{ this.VersionInfoChecked__ = true; return this; }
	}
	#endregion
}
