/********************************************
Copyright  2015, SN Servicing, Inc.

THIS FILE WAS AUTO-GENERATED BY A TOOL.
DO NOT EDIT THE CONTENTS MANUALLY.
********************************************/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Runtime.Serialization;

namespace Snsc.Database.Core
{
	#region Class SecureShare_up_sdii_sdiLogging
	/// <summary>
	/// SPEW Core.SecureShare.SecureShare_up_sdii_sdiLogging
	/// Generated: 2015-08-26 16:18 (utc) on eur-sql-stg by jprofumo.
	/// </summary>
	/// <remarks>
	/// Provides a wrapper for execution of the up_sdii_sdiLogging stored procedure.
	/// </remarks>
	[Serializable]
	public class SecureShare_up_sdii_sdiLogging : Snsc.Base.Data.StoredProcedureExecutorBase
	{
		private void Init()
		{
			this.dbname = "Core";
			this.procname = "[SecureShare].[up_sdii_sdiLogging]";
			this.versionInfo__ = 524324050;
			this.md5VersionInfo = "442EF7C9C2F6FA301B23322398C9CC";
			InitializeParameters();
		}
		
		#region Class SecureShare_up_sdii_sdiLogging Constructors
		/// <summary>
		/// Constructor.
		/// </summary>
		public SecureShare_up_sdii_sdiLogging()
		{
			Init();
		}

		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="cn">SqlConnection to use when executing the procedure.</param>
		public SecureShare_up_sdii_sdiLogging(SqlConnection cn) : base(cn)
		{
			Init();
		}

		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="cn">SqlConnection to use when executing the procedure.</param>
		/// <param name="tx">SqlTransaction to use when executing the procedure.</param>
		public SecureShare_up_sdii_sdiLogging(SqlConnection cn, SqlTransaction tx) : base(cn, tx)
		{
			Init();
		}

		/// <summary>
		/// Special constructor for DeSerialization.
		/// </summary>
		protected SecureShare_up_sdii_sdiLogging(SerializationInfo info, StreamingContext context) : base(info, context)
		{
		}
		#endregion

		// Private instance of the nested Parameters class
		private SecureShare_up_sdii_sdiLoggingParameters __paramsInstance = null;

		/// <summary>
		/// Parameters for the procedure.
		/// </summary>
		public SecureShare_up_sdii_sdiLoggingParameters Parameters
		{
			get
			{
				if(this.__paramsInstance == null)
					throw new Snsc.Base.Data.ParametersNotInitializedException(this);
				return this.__paramsInstance;
			}
		}

		/// <summary>
		/// Sets up parameters and adds them to the Command object.
		/// </summary>
		protected override void InitializeParameters()
		{
			__paramsInstance = new SecureShare_up_sdii_sdiLoggingParameters(Command);
			this.Parameters.Reset();
		}

		#region SecureShare_up_sdii_sdiLogging Parameters class
		/// <summary>
		/// Nested class containing the parameters for the procedure.
		/// </summary>
		[Serializable]
		public class SecureShare_up_sdii_sdiLoggingParameters
		{
			private SqlParameterCollection __paramsCollection = null;

			/// <summary>
			/// Sets value of all SqlParameters to DBNull.Value.
			/// </summary>
			public void Reset()
			{
				foreach(SqlParameter p in __paramsCollection)
				{
					p.Value = DBNull.Value;
				}
			}

			#region SecureShare_up_sdii_sdiLogging Parameters Initialization
			/// <summary>
			/// Constructor.
			/// </summary>
			public SecureShare_up_sdii_sdiLoggingParameters(SqlCommand cmd)
			{
				// Grab ref to the parameters collection for use in the Reset() method.
				this.__paramsCollection = cmd.Parameters;
				SqlParameter p = null;
				//---- Parameter @LogSubTypeID
				p = new SqlParameter(); p.ParameterName = "@LogSubTypeID"; p.SqlDbType = System.Data.SqlDbType.Int; p.Direction = System.Data.ParameterDirection.Input; p.Size = 0; p.Precision = 10; p.Scale = 0; cmd.Parameters.Add(p); this._private_LogSubTypeID_ = p;
				//---- Parameter @Value1
				p = new SqlParameter(); p.ParameterName = "@Value1"; p.SqlDbType = System.Data.SqlDbType.VarChar; p.Direction = System.Data.ParameterDirection.Input; p.Size = 100; p.Precision = 0; p.Scale = 0; cmd.Parameters.Add(p); this._private_Value1_ = p;
				//---- Parameter @Value2
				p = new SqlParameter(); p.ParameterName = "@Value2"; p.SqlDbType = System.Data.SqlDbType.VarChar; p.Direction = System.Data.ParameterDirection.Input; p.Size = 100; p.Precision = 0; p.Scale = 0; cmd.Parameters.Add(p); this._private_Value2_ = p;
				//---- Parameter @PerformedByAmsUserID
				p = new SqlParameter(); p.ParameterName = "@PerformedByAmsUserID"; p.SqlDbType = System.Data.SqlDbType.Int; p.Direction = System.Data.ParameterDirection.Input; p.Size = 0; p.Precision = 10; p.Scale = 0; cmd.Parameters.Add(p); this._private_PerformedByAmsUserID_ = p;
				//---- Parameter @PerformedByAspNetUserID
				p = new SqlParameter(); p.ParameterName = "@PerformedByAspNetUserID"; p.SqlDbType = System.Data.SqlDbType.UniqueIdentifier; p.Direction = System.Data.ParameterDirection.Input; p.Size = 0; p.Precision = 0; p.Scale = 0; cmd.Parameters.Add(p); this._private_PerformedByAspNetUserID_ = p;
				//---- Parameter @LogSourceId
				p = new SqlParameter(); p.ParameterName = "@LogSourceId"; p.SqlDbType = System.Data.SqlDbType.Int; p.Direction = System.Data.ParameterDirection.Input; p.Size = 0; p.Precision = 10; p.Scale = 0; cmd.Parameters.Add(p); this._private_LogSourceId_ = p;
				//---- Parameter @LogID
				p = new SqlParameter(); p.ParameterName = "@LogID"; p.SqlDbType = System.Data.SqlDbType.BigInt; p.Direction = System.Data.ParameterDirection.InputOutput; p.Size = 0; p.Precision = 19; p.Scale = 0; cmd.Parameters.Add(p); this._private_LogID_ = p;
				// Add hard-coded return value
				p = new SqlParameter(); p.ParameterName = "@RETURN_VALUE"; p.SqlDbType = System.Data.SqlDbType.Int; p.Direction = System.Data.ParameterDirection.ReturnValue; cmd.Parameters.Add(p); this._private__returnvalue__ = p;
			}
			#endregion
			private SqlParameter _private_LogSubTypeID_ = null;
			private SqlParameter _private_Value1_ = null;
			private SqlParameter _private_Value2_ = null;
			private SqlParameter _private_PerformedByAmsUserID_ = null;
			private SqlParameter _private_PerformedByAspNetUserID_ = null;
			private SqlParameter _private_LogSourceId_ = null;
			private SqlParameter _private_LogID_ = null;
			private SqlParameter _private__returnvalue__ = null;

			/// <summary>
			/// Provides access to parameters by name.
			/// </summary>
			public SqlParameter this[string paramName]
			{
				get
				{
					string idx = paramName.Replace("@", "").ToLower();
					SqlParameter retval = null;
					switch(idx)
					{
						case "logsubtypeid": retval = this._private_LogSubTypeID_; break;
						case "value1": retval = this._private_Value1_; break;
						case "value2": retval = this._private_Value2_; break;
						case "performedbyamsuserid": retval = this._private_PerformedByAmsUserID_; break;
						case "performedbyaspnetuserid": retval = this._private_PerformedByAspNetUserID_; break;
						case "logsourceid": retval = this._private_LogSourceId_; break;
						case "logid": retval = this._private_LogID_; break;
						case "__returnvalue__": retval = this._private__returnvalue__; break;
					}
					return retval;
				}
			}

			/// <summary>@LogSubTypeID int || Direction: Input || Prec: 10 || Scale: 0</summary>
			public SqlParameter LogSubTypeID_ { get { return _private_LogSubTypeID_; } }
			/// <summary>@Value1 varchar(100) || Direction: Input || Prec: 0 || Scale: 0</summary>
			public SqlParameter Value1_ { get { return _private_Value1_; } }
			/// <summary>@Value2 varchar(100) || Direction: Input || Prec: 0 || Scale: 0</summary>
			public SqlParameter Value2_ { get { return _private_Value2_; } }
			/// <summary>@PerformedByAmsUserID int || Direction: Input || Prec: 10 || Scale: 0</summary>
			public SqlParameter PerformedByAmsUserID_ { get { return _private_PerformedByAmsUserID_; } }
			/// <summary>@PerformedByAspNetUserID uniqueidentifier || Direction: Input || Prec: 0 || Scale: 0</summary>
			public SqlParameter PerformedByAspNetUserID_ { get { return _private_PerformedByAspNetUserID_; } }
			/// <summary>@LogSourceId int || Direction: Input || Prec: 10 || Scale: 0</summary>
			public SqlParameter LogSourceId_ { get { return _private_LogSourceId_; } }
			/// <summary>@LogID bigint || Direction: InputOutput || Prec: 19 || Scale: 0</summary>
			public SqlParameter LogID_ { get { return _private_LogID_; } }
			/// <summary>@__returnvalue__ int || Direction: ReturnValue</summary>
			public SqlParameter ReturnValue__ { get { return this._private__returnvalue__; } }
		}
		#endregion

		/// <summary>Must be called before calling any Execute... method.</summary>
		public Snsc.Base.Data.StoredProcedureExecutorBase VersionInfo524324050()
		{ this.VersionInfoChecked__ = true; return this; }

		/// <summary>Must be called before calling any Execute... method.</summary>
		public Snsc.Base.Data.StoredProcedureExecutorBase VersionInfo442EF7C9C2F6FA301B23322398C9CC()
		{ this.VersionInfoChecked__ = true; return this; }
	}
	#endregion
}
