/********************************************
Copyright  2015, SN Servicing, Inc.

THIS FILE WAS AUTO-GENERATED BY A TOOL.
DO NOT EDIT THE CONTENTS MANUALLY.
********************************************/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Runtime.Serialization;

namespace Snsc.Database.Core
{
	#region Class SecureShare_up_SDIi_sdiFileSharingZone
	/// <summary>
	/// SPEW Core.SecureShare.SecureShare_up_SDIi_sdiFileSharingZone
	/// Generated: 2015-08-26 16:24 (utc) on eur-sql-stg by jprofumo.
	/// </summary>
	/// <remarks>
	/// Provides a wrapper for execution of the up_SDIi_sdiFileSharingZone stored procedure.
	/// </remarks>
	[Serializable]
	public class SecureShare_up_SDIi_sdiFileSharingZone : Snsc.Base.Data.StoredProcedureExecutorBase
	{
		private void Init()
		{
			this.dbname = "Core";
			this.procname = "[SecureShare].[up_SDIi_sdiFileSharingZone]";
			this.versionInfo__ = 1853360951;
			this.md5VersionInfo = "3E1ED02E5C50B97B420606AF0737";
			InitializeParameters();
		}
		
		#region Class SecureShare_up_SDIi_sdiFileSharingZone Constructors
		/// <summary>
		/// Constructor.
		/// </summary>
		public SecureShare_up_SDIi_sdiFileSharingZone()
		{
			Init();
		}

		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="cn">SqlConnection to use when executing the procedure.</param>
		public SecureShare_up_SDIi_sdiFileSharingZone(SqlConnection cn) : base(cn)
		{
			Init();
		}

		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="cn">SqlConnection to use when executing the procedure.</param>
		/// <param name="tx">SqlTransaction to use when executing the procedure.</param>
		public SecureShare_up_SDIi_sdiFileSharingZone(SqlConnection cn, SqlTransaction tx) : base(cn, tx)
		{
			Init();
		}

		/// <summary>
		/// Special constructor for DeSerialization.
		/// </summary>
		protected SecureShare_up_SDIi_sdiFileSharingZone(SerializationInfo info, StreamingContext context) : base(info, context)
		{
		}
		#endregion

		// Private instance of the nested Parameters class
		private SecureShare_up_SDIi_sdiFileSharingZoneParameters __paramsInstance = null;

		/// <summary>
		/// Parameters for the procedure.
		/// </summary>
		public SecureShare_up_SDIi_sdiFileSharingZoneParameters Parameters
		{
			get
			{
				if(this.__paramsInstance == null)
					throw new Snsc.Base.Data.ParametersNotInitializedException(this);
				return this.__paramsInstance;
			}
		}

		/// <summary>
		/// Sets up parameters and adds them to the Command object.
		/// </summary>
		protected override void InitializeParameters()
		{
			__paramsInstance = new SecureShare_up_SDIi_sdiFileSharingZoneParameters(Command);
			this.Parameters.Reset();
		}

		#region SecureShare_up_SDIi_sdiFileSharingZone Parameters class
		/// <summary>
		/// Nested class containing the parameters for the procedure.
		/// </summary>
		[Serializable]
		public class SecureShare_up_SDIi_sdiFileSharingZoneParameters
		{
			private SqlParameterCollection __paramsCollection = null;

			/// <summary>
			/// Sets value of all SqlParameters to DBNull.Value.
			/// </summary>
			public void Reset()
			{
				foreach(SqlParameter p in __paramsCollection)
				{
					p.Value = DBNull.Value;
				}
			}

			#region SecureShare_up_SDIi_sdiFileSharingZone Parameters Initialization
			/// <summary>
			/// Constructor.
			/// </summary>
			public SecureShare_up_SDIi_sdiFileSharingZoneParameters(SqlCommand cmd)
			{
				// Grab ref to the parameters collection for use in the Reset() method.
				this.__paramsCollection = cmd.Parameters;
				SqlParameter p = null;
				//---- Parameter @FileSharingZoneID
				p = new SqlParameter(); p.ParameterName = "@FileSharingZoneID"; p.SqlDbType = System.Data.SqlDbType.Int; p.Direction = System.Data.ParameterDirection.InputOutput; p.Size = 0; p.Precision = 10; p.Scale = 0; cmd.Parameters.Add(p); this._private_FileSharingZoneID_ = p;
				//---- Parameter @PrimaryObjectID
				p = new SqlParameter(); p.ParameterName = "@PrimaryObjectID"; p.SqlDbType = System.Data.SqlDbType.VarChar; p.Direction = System.Data.ParameterDirection.Input; p.Size = 100; p.Precision = 0; p.Scale = 0; cmd.Parameters.Add(p); this._private_PrimaryObjectID_ = p;
				//---- Parameter @SecondaryObjectID
				p = new SqlParameter(); p.ParameterName = "@SecondaryObjectID"; p.SqlDbType = System.Data.SqlDbType.VarChar; p.Direction = System.Data.ParameterDirection.Input; p.Size = 100; p.Precision = 0; p.Scale = 0; cmd.Parameters.Add(p); this._private_SecondaryObjectID_ = p;
				//---- Parameter @FileSharingZoneTypeID
				p = new SqlParameter(); p.ParameterName = "@FileSharingZoneTypeID"; p.SqlDbType = System.Data.SqlDbType.Int; p.Direction = System.Data.ParameterDirection.Input; p.Size = 0; p.Precision = 10; p.Scale = 0; cmd.Parameters.Add(p); this._private_FileSharingZoneTypeID_ = p;
				//---- Parameter @Description
				p = new SqlParameter(); p.ParameterName = "@Description"; p.SqlDbType = System.Data.SqlDbType.VarChar; p.Direction = System.Data.ParameterDirection.Input; p.Size = 1024; p.Precision = 0; p.Scale = 0; cmd.Parameters.Add(p); this._private_Description_ = p;
				// Add hard-coded return value
				p = new SqlParameter(); p.ParameterName = "@RETURN_VALUE"; p.SqlDbType = System.Data.SqlDbType.Int; p.Direction = System.Data.ParameterDirection.ReturnValue; cmd.Parameters.Add(p); this._private__returnvalue__ = p;
			}
			#endregion
			private SqlParameter _private_FileSharingZoneID_ = null;
			private SqlParameter _private_PrimaryObjectID_ = null;
			private SqlParameter _private_SecondaryObjectID_ = null;
			private SqlParameter _private_FileSharingZoneTypeID_ = null;
			private SqlParameter _private_Description_ = null;
			private SqlParameter _private__returnvalue__ = null;

			/// <summary>
			/// Provides access to parameters by name.
			/// </summary>
			public SqlParameter this[string paramName]
			{
				get
				{
					string idx = paramName.Replace("@", "").ToLower();
					SqlParameter retval = null;
					switch(idx)
					{
						case "filesharingzoneid": retval = this._private_FileSharingZoneID_; break;
						case "primaryobjectid": retval = this._private_PrimaryObjectID_; break;
						case "secondaryobjectid": retval = this._private_SecondaryObjectID_; break;
						case "filesharingzonetypeid": retval = this._private_FileSharingZoneTypeID_; break;
						case "description": retval = this._private_Description_; break;
						case "__returnvalue__": retval = this._private__returnvalue__; break;
					}
					return retval;
				}
			}

			/// <summary>@FileSharingZoneID int || Direction: InputOutput || Prec: 10 || Scale: 0</summary>
			public SqlParameter FileSharingZoneID_ { get { return _private_FileSharingZoneID_; } }
			/// <summary>@PrimaryObjectID varchar(100) || Direction: Input || Prec: 0 || Scale: 0</summary>
			public SqlParameter PrimaryObjectID_ { get { return _private_PrimaryObjectID_; } }
			/// <summary>@SecondaryObjectID varchar(100) || Direction: Input || Prec: 0 || Scale: 0</summary>
			public SqlParameter SecondaryObjectID_ { get { return _private_SecondaryObjectID_; } }
			/// <summary>@FileSharingZoneTypeID int || Direction: Input || Prec: 10 || Scale: 0</summary>
			public SqlParameter FileSharingZoneTypeID_ { get { return _private_FileSharingZoneTypeID_; } }
			/// <summary>@Description varchar(1024) || Direction: Input || Prec: 0 || Scale: 0</summary>
			public SqlParameter Description_ { get { return _private_Description_; } }
			/// <summary>@__returnvalue__ int || Direction: ReturnValue</summary>
			public SqlParameter ReturnValue__ { get { return this._private__returnvalue__; } }
		}
		#endregion

		/// <summary>Must be called before calling any Execute... method.</summary>
		public Snsc.Base.Data.StoredProcedureExecutorBase VersionInfo1853360951()
		{ this.VersionInfoChecked__ = true; return this; }

		/// <summary>Must be called before calling any Execute... method.</summary>
		public Snsc.Base.Data.StoredProcedureExecutorBase VersionInfo3E1ED02E5C50B97B420606AF0737()
		{ this.VersionInfoChecked__ = true; return this; }
	}
	#endregion
}
