/********************************************
Copyright  2015, SN Servicing, Inc.

THIS FILE WAS AUTO-GENERATED BY A TOOL.
DO NOT EDIT THE CONTENTS MANUALLY.
********************************************/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Runtime.Serialization;

namespace Snsc.Database.Core
{
	#region Class SecureShare_up_SDIiu_sdiFileSharingZonePermissionAmsUser
	/// <summary>
	/// SPEW Core.SecureShare.SecureShare_up_SDIiu_sdiFileSharingZonePermissionAmsUser
	/// Generated: 2015-08-26 16:18 (utc) on eur-sql-stg by jprofumo.
	/// </summary>
	/// <remarks>
	/// Provides a wrapper for execution of the up_SDIiu_sdiFileSharingZonePermissionAmsUser stored procedure.
	/// </remarks>
	[Serializable]
	public class SecureShare_up_SDIiu_sdiFileSharingZonePermissionAmsUser : Snsc.Base.Data.StoredProcedureExecutorBase
	{
		private void Init()
		{
			this.dbname = "Core";
			this.procname = "[SecureShare].[up_SDIiu_sdiFileSharingZonePermissionAmsUser]";
			this.versionInfo__ = 1322954620;
			this.md5VersionInfo = "54D5222AE683838AE0EFFEC75A3F6A2";
			InitializeParameters();
		}
		
		#region Class SecureShare_up_SDIiu_sdiFileSharingZonePermissionAmsUser Constructors
		/// <summary>
		/// Constructor.
		/// </summary>
		public SecureShare_up_SDIiu_sdiFileSharingZonePermissionAmsUser()
		{
			Init();
		}

		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="cn">SqlConnection to use when executing the procedure.</param>
		public SecureShare_up_SDIiu_sdiFileSharingZonePermissionAmsUser(SqlConnection cn) : base(cn)
		{
			Init();
		}

		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="cn">SqlConnection to use when executing the procedure.</param>
		/// <param name="tx">SqlTransaction to use when executing the procedure.</param>
		public SecureShare_up_SDIiu_sdiFileSharingZonePermissionAmsUser(SqlConnection cn, SqlTransaction tx) : base(cn, tx)
		{
			Init();
		}

		/// <summary>
		/// Special constructor for DeSerialization.
		/// </summary>
		protected SecureShare_up_SDIiu_sdiFileSharingZonePermissionAmsUser(SerializationInfo info, StreamingContext context) : base(info, context)
		{
		}
		#endregion

		// Private instance of the nested Parameters class
		private SecureShare_up_SDIiu_sdiFileSharingZonePermissionAmsUserParameters __paramsInstance = null;

		/// <summary>
		/// Parameters for the procedure.
		/// </summary>
		public SecureShare_up_SDIiu_sdiFileSharingZonePermissionAmsUserParameters Parameters
		{
			get
			{
				if(this.__paramsInstance == null)
					throw new Snsc.Base.Data.ParametersNotInitializedException(this);
				return this.__paramsInstance;
			}
		}

		/// <summary>
		/// Sets up parameters and adds them to the Command object.
		/// </summary>
		protected override void InitializeParameters()
		{
			__paramsInstance = new SecureShare_up_SDIiu_sdiFileSharingZonePermissionAmsUserParameters(Command);
			this.Parameters.Reset();
		}

		#region SecureShare_up_SDIiu_sdiFileSharingZonePermissionAmsUser Parameters class
		/// <summary>
		/// Nested class containing the parameters for the procedure.
		/// </summary>
		[Serializable]
		public class SecureShare_up_SDIiu_sdiFileSharingZonePermissionAmsUserParameters
		{
			private SqlParameterCollection __paramsCollection = null;

			/// <summary>
			/// Sets value of all SqlParameters to DBNull.Value.
			/// </summary>
			public void Reset()
			{
				foreach(SqlParameter p in __paramsCollection)
				{
					p.Value = DBNull.Value;
				}
			}

			#region SecureShare_up_SDIiu_sdiFileSharingZonePermissionAmsUser Parameters Initialization
			/// <summary>
			/// Constructor.
			/// </summary>
			public SecureShare_up_SDIiu_sdiFileSharingZonePermissionAmsUserParameters(SqlCommand cmd)
			{
				// Grab ref to the parameters collection for use in the Reset() method.
				this.__paramsCollection = cmd.Parameters;
				SqlParameter p = null;
				//---- Parameter @FileSharingZoneID
				p = new SqlParameter(); p.ParameterName = "@FileSharingZoneID"; p.SqlDbType = System.Data.SqlDbType.Int; p.Direction = System.Data.ParameterDirection.Input; p.Size = 0; p.Precision = 10; p.Scale = 0; cmd.Parameters.Add(p); this._private_FileSharingZoneID_ = p;
				//---- Parameter @AmsUserID
				p = new SqlParameter(); p.ParameterName = "@AmsUserID"; p.SqlDbType = System.Data.SqlDbType.BigInt; p.Direction = System.Data.ParameterDirection.Input; p.Size = 0; p.Precision = 19; p.Scale = 0; cmd.Parameters.Add(p); this._private_AmsUserID_ = p;
				//---- Parameter @NotificationOptIn
				p = new SqlParameter(); p.ParameterName = "@NotificationOptIn"; p.SqlDbType = System.Data.SqlDbType.Bit; p.Direction = System.Data.ParameterDirection.Input; p.Size = 0; p.Precision = 0; p.Scale = 0; cmd.Parameters.Add(p); this._private_NotificationOptIn_ = p;
				//---- Parameter @nullMap
				p = new SqlParameter(); p.ParameterName = "@nullMap"; p.SqlDbType = System.Data.SqlDbType.VarBinary; p.Direction = System.Data.ParameterDirection.Input; p.Size = 1; p.Precision = 0; p.Scale = 0; cmd.Parameters.Add(p); this._private_nullMap_ = p;
				// Add hard-coded return value
				p = new SqlParameter(); p.ParameterName = "@RETURN_VALUE"; p.SqlDbType = System.Data.SqlDbType.Int; p.Direction = System.Data.ParameterDirection.ReturnValue; cmd.Parameters.Add(p); this._private__returnvalue__ = p;
			}
			#endregion
			private SqlParameter _private_FileSharingZoneID_ = null;
			private SqlParameter _private_AmsUserID_ = null;
			private SqlParameter _private_NotificationOptIn_ = null;
			private SqlParameter _private_nullMap_ = null;
			private SqlParameter _private__returnvalue__ = null;

			/// <summary>
			/// Provides access to parameters by name.
			/// </summary>
			public SqlParameter this[string paramName]
			{
				get
				{
					string idx = paramName.Replace("@", "").ToLower();
					SqlParameter retval = null;
					switch(idx)
					{
						case "filesharingzoneid": retval = this._private_FileSharingZoneID_; break;
						case "amsuserid": retval = this._private_AmsUserID_; break;
						case "notificationoptin": retval = this._private_NotificationOptIn_; break;
						case "nullmap": retval = this._private_nullMap_; break;
						case "__returnvalue__": retval = this._private__returnvalue__; break;
					}
					return retval;
				}
			}

			/// <summary>@FileSharingZoneID int || Direction: Input || Prec: 10 || Scale: 0</summary>
			public SqlParameter FileSharingZoneID_ { get { return _private_FileSharingZoneID_; } }
			/// <summary>@AmsUserID bigint || Direction: Input || Prec: 19 || Scale: 0</summary>
			public SqlParameter AmsUserID_ { get { return _private_AmsUserID_; } }
			/// <summary>@NotificationOptIn bit || Direction: Input || Prec: 0 || Scale: 0</summary>
			public SqlParameter NotificationOptIn_ { get { return _private_NotificationOptIn_; } }
			/// <summary>@nullMap varbinary(1) || Direction: Input || Prec: 0 || Scale: 0</summary>
			public SqlParameter nullMap_ { get { return _private_nullMap_; } }
			/// <summary>@__returnvalue__ int || Direction: ReturnValue</summary>
			public SqlParameter ReturnValue__ { get { return this._private__returnvalue__; } }
		}
		#endregion

		/// <summary>Must be called before calling any Execute... method.</summary>
		public Snsc.Base.Data.StoredProcedureExecutorBase VersionInfo1322954620()
		{ this.VersionInfoChecked__ = true; return this; }

		/// <summary>Must be called before calling any Execute... method.</summary>
		public Snsc.Base.Data.StoredProcedureExecutorBase VersionInfo54D5222AE683838AE0EFFEC75A3F6A2()
		{ this.VersionInfoChecked__ = true; return this; }
	}
	#endregion
}
