/********************************************
Copyright  2015, SN Servicing, Inc.

THIS FILE WAS AUTO-GENERATED BY A TOOL.
DO NOT EDIT THE CONTENTS MANUALLY.
********************************************/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Runtime.Serialization;

namespace Snsc.Database.Core
{
	#region Class SecureShare_up_SDIi_sdiSharedFile
	/// <summary>
	/// SPEW Core.SecureShare.SecureShare_up_SDIi_sdiSharedFile
	/// Generated: 2015-07-23 22:03 (utc) on eur-sql-stg by jprofumo.
	/// </summary>
	/// <remarks>
	/// Provides a wrapper for execution of the up_SDIi_sdiSharedFile stored procedure.
	/// </remarks>
	[Serializable]
	public class SecureShare_up_SDIi_sdiSharedFile : Snsc.Base.Data.StoredProcedureExecutorBase
	{
		private void Init()
		{
			this.dbname = "Core";
			this.procname = "[SecureShare].[up_SDIi_sdiSharedFile]";
			this.versionInfo__ = 28159290;
			this.md5VersionInfo = "D2297686A203592FFA52D18C6CA69F4";
			InitializeParameters();
		}
		
		#region Class SecureShare_up_SDIi_sdiSharedFile Constructors
		/// <summary>
		/// Constructor.
		/// </summary>
		public SecureShare_up_SDIi_sdiSharedFile()
		{
			Init();
		}

		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="cn">SqlConnection to use when executing the procedure.</param>
		public SecureShare_up_SDIi_sdiSharedFile(SqlConnection cn) : base(cn)
		{
			Init();
		}

		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="cn">SqlConnection to use when executing the procedure.</param>
		/// <param name="tx">SqlTransaction to use when executing the procedure.</param>
		public SecureShare_up_SDIi_sdiSharedFile(SqlConnection cn, SqlTransaction tx) : base(cn, tx)
		{
			Init();
		}

		/// <summary>
		/// Special constructor for DeSerialization.
		/// </summary>
		protected SecureShare_up_SDIi_sdiSharedFile(SerializationInfo info, StreamingContext context) : base(info, context)
		{
		}
		#endregion

		// Private instance of the nested Parameters class
		private SecureShare_up_SDIi_sdiSharedFileParameters __paramsInstance = null;

		/// <summary>
		/// Parameters for the procedure.
		/// </summary>
		public SecureShare_up_SDIi_sdiSharedFileParameters Parameters
		{
			get
			{
				if(this.__paramsInstance == null)
					throw new Snsc.Base.Data.ParametersNotInitializedException(this);
				return this.__paramsInstance;
			}
		}

		/// <summary>
		/// Sets up parameters and adds them to the Command object.
		/// </summary>
		protected override void InitializeParameters()
		{
			__paramsInstance = new SecureShare_up_SDIi_sdiSharedFileParameters(Command);
			this.Parameters.Reset();
		}

		#region SecureShare_up_SDIi_sdiSharedFile Parameters class
		/// <summary>
		/// Nested class containing the parameters for the procedure.
		/// </summary>
		[Serializable]
		public class SecureShare_up_SDIi_sdiSharedFileParameters
		{
			private SqlParameterCollection __paramsCollection = null;

			/// <summary>
			/// Sets value of all SqlParameters to DBNull.Value.
			/// </summary>
			public void Reset()
			{
				foreach(SqlParameter p in __paramsCollection)
				{
					p.Value = DBNull.Value;
				}
			}

			#region SecureShare_up_SDIi_sdiSharedFile Parameters Initialization
			/// <summary>
			/// Constructor.
			/// </summary>
			public SecureShare_up_SDIi_sdiSharedFileParameters(SqlCommand cmd)
			{
				// Grab ref to the parameters collection for use in the Reset() method.
				this.__paramsCollection = cmd.Parameters;
				SqlParameter p = null;
				//---- Parameter @SharedFileID
				p = new SqlParameter(); p.ParameterName = "@SharedFileID"; p.SqlDbType = System.Data.SqlDbType.Int; p.Direction = System.Data.ParameterDirection.InputOutput; p.Size = 0; p.Precision = 10; p.Scale = 0; cmd.Parameters.Add(p); this._private_SharedFileID_ = p;
				//---- Parameter @Name
				p = new SqlParameter(); p.ParameterName = "@Name"; p.SqlDbType = System.Data.SqlDbType.VarChar; p.Direction = System.Data.ParameterDirection.Input; p.Size = 100; p.Precision = 0; p.Scale = 0; cmd.Parameters.Add(p); this._private_Name_ = p;
				//---- Parameter @Description
				p = new SqlParameter(); p.ParameterName = "@Description"; p.SqlDbType = System.Data.SqlDbType.VarChar; p.Direction = System.Data.ParameterDirection.Input; p.Size = 1024; p.Precision = 0; p.Scale = 0; cmd.Parameters.Add(p); this._private_Description_ = p;
				//---- Parameter @DiskFileName
				p = new SqlParameter(); p.ParameterName = "@DiskFileName"; p.SqlDbType = System.Data.SqlDbType.VarChar; p.Direction = System.Data.ParameterDirection.Input; p.Size = 512; p.Precision = 0; p.Scale = 0; cmd.Parameters.Add(p); this._private_DiskFileName_ = p;
				//---- Parameter @FileSharingZoneID
				p = new SqlParameter(); p.ParameterName = "@FileSharingZoneID"; p.SqlDbType = System.Data.SqlDbType.Int; p.Direction = System.Data.ParameterDirection.Input; p.Size = 0; p.Precision = 10; p.Scale = 0; cmd.Parameters.Add(p); this._private_FileSharingZoneID_ = p;
				//---- Parameter @UploadedByAspNetUser
				p = new SqlParameter(); p.ParameterName = "@UploadedByAspNetUser"; p.SqlDbType = System.Data.SqlDbType.UniqueIdentifier; p.Direction = System.Data.ParameterDirection.Input; p.Size = 0; p.Precision = 0; p.Scale = 0; cmd.Parameters.Add(p); this._private_UploadedByAspNetUser_ = p;
				//---- Parameter @UploadedByAmsUser
				p = new SqlParameter(); p.ParameterName = "@UploadedByAmsUser"; p.SqlDbType = System.Data.SqlDbType.Int; p.Direction = System.Data.ParameterDirection.Input; p.Size = 0; p.Precision = 10; p.Scale = 0; cmd.Parameters.Add(p); this._private_UploadedByAmsUser_ = p;
				//---- Parameter @CreatedOnUTC
				p = new SqlParameter(); p.ParameterName = "@CreatedOnUTC"; p.SqlDbType = System.Data.SqlDbType.DateTime; p.Direction = System.Data.ParameterDirection.Input; p.Size = 0; p.Precision = 0; p.Scale = 0; cmd.Parameters.Add(p); this._private_CreatedOnUTC_ = p;
				//---- Parameter @FileSizeBytes
				p = new SqlParameter(); p.ParameterName = "@FileSizeBytes"; p.SqlDbType = System.Data.SqlDbType.Int; p.Direction = System.Data.ParameterDirection.Input; p.Size = 0; p.Precision = 10; p.Scale = 0; cmd.Parameters.Add(p); this._private_FileSizeBytes_ = p;
				// Add hard-coded return value
				p = new SqlParameter(); p.ParameterName = "@RETURN_VALUE"; p.SqlDbType = System.Data.SqlDbType.Int; p.Direction = System.Data.ParameterDirection.ReturnValue; cmd.Parameters.Add(p); this._private__returnvalue__ = p;
			}
			#endregion
			private SqlParameter _private_SharedFileID_ = null;
			private SqlParameter _private_Name_ = null;
			private SqlParameter _private_Description_ = null;
			private SqlParameter _private_DiskFileName_ = null;
			private SqlParameter _private_FileSharingZoneID_ = null;
			private SqlParameter _private_UploadedByAspNetUser_ = null;
			private SqlParameter _private_UploadedByAmsUser_ = null;
			private SqlParameter _private_CreatedOnUTC_ = null;
			private SqlParameter _private_FileSizeBytes_ = null;
			private SqlParameter _private__returnvalue__ = null;

			/// <summary>
			/// Provides access to parameters by name.
			/// </summary>
			public SqlParameter this[string paramName]
			{
				get
				{
					string idx = paramName.Replace("@", "").ToLower();
					SqlParameter retval = null;
					switch(idx)
					{
						case "sharedfileid": retval = this._private_SharedFileID_; break;
						case "name": retval = this._private_Name_; break;
						case "description": retval = this._private_Description_; break;
						case "diskfilename": retval = this._private_DiskFileName_; break;
						case "filesharingzoneid": retval = this._private_FileSharingZoneID_; break;
						case "uploadedbyaspnetuser": retval = this._private_UploadedByAspNetUser_; break;
						case "uploadedbyamsuser": retval = this._private_UploadedByAmsUser_; break;
						case "createdonutc": retval = this._private_CreatedOnUTC_; break;
						case "filesizebytes": retval = this._private_FileSizeBytes_; break;
						case "__returnvalue__": retval = this._private__returnvalue__; break;
					}
					return retval;
				}
			}

			/// <summary>@SharedFileID int || Direction: InputOutput || Prec: 10 || Scale: 0</summary>
			public SqlParameter SharedFileID_ { get { return _private_SharedFileID_; } }
			/// <summary>@Name varchar(100) || Direction: Input || Prec: 0 || Scale: 0</summary>
			public SqlParameter Name_ { get { return _private_Name_; } }
			/// <summary>@Description varchar(1024) || Direction: Input || Prec: 0 || Scale: 0</summary>
			public SqlParameter Description_ { get { return _private_Description_; } }
			/// <summary>@DiskFileName varchar(512) || Direction: Input || Prec: 0 || Scale: 0</summary>
			public SqlParameter DiskFileName_ { get { return _private_DiskFileName_; } }
			/// <summary>@FileSharingZoneID int || Direction: Input || Prec: 10 || Scale: 0</summary>
			public SqlParameter FileSharingZoneID_ { get { return _private_FileSharingZoneID_; } }
			/// <summary>@UploadedByAspNetUser uniqueidentifier || Direction: Input || Prec: 0 || Scale: 0</summary>
			public SqlParameter UploadedByAspNetUser_ { get { return _private_UploadedByAspNetUser_; } }
			/// <summary>@UploadedByAmsUser int || Direction: Input || Prec: 10 || Scale: 0</summary>
			public SqlParameter UploadedByAmsUser_ { get { return _private_UploadedByAmsUser_; } }
			/// <summary>@CreatedOnUTC datetime || Direction: Input || Prec: 0 || Scale: 0</summary>
			public SqlParameter CreatedOnUTC_ { get { return _private_CreatedOnUTC_; } }
			/// <summary>@FileSizeBytes int || Direction: Input || Prec: 10 || Scale: 0</summary>
			public SqlParameter FileSizeBytes_ { get { return _private_FileSizeBytes_; } }
			/// <summary>@__returnvalue__ int || Direction: ReturnValue</summary>
			public SqlParameter ReturnValue__ { get { return this._private__returnvalue__; } }
		}
		#endregion

		/// <summary>Must be called before calling any Execute... method.</summary>
		public Snsc.Base.Data.StoredProcedureExecutorBase VersionInfo28159290()
		{ this.VersionInfoChecked__ = true; return this; }

		/// <summary>Must be called before calling any Execute... method.</summary>
		public Snsc.Base.Data.StoredProcedureExecutorBase VersionInfoD2297686A203592FFA52D18C6CA69F4()
		{ this.VersionInfoChecked__ = true; return this; }
	}
	#endregion
}
